### ISSUE TITLE
Tile counter overflow

### ISSUE THREAD

**Issue by sakvaka** [s3tbx-fub-csiro/s3tbx-fub-csiro#1]
**Version**: FuB Csiro Op v. 1.0.0.0.5.3 (C version), SNAP 8.0, Linux platform, Python 3.6.15 packaged by `conda-forge`, running from `gpt`
**Description of issue**: When computing FubCsiroOp operator from command line with the following command

```bash
SNAP_MEM=24576M
SNAP_CORES=3
SNAP_CACHE=18432M
gptparams="-J-Xmx$SNAP_MEM -q $SNAP_CORES -c $SNAP_CACHE"

cat >> ~/FuB.properties << EOF
computeCHL=true
computeYEL=true
computeTSM=true
computeATM=true
computeJaco=false
computeeVT=true
computeFast=true
preMaskingExpressionOLCI=
EOF

filename=S3B_OL_1_EFR____20220403T235832_20220404T000132_20220405T032745_0179_064_230_1980_MAR_O_NT_002.SEN3
outname=FuB_test.dim

gpt FubCsiroOp -e -x $gptparams -p ~/FuB.properties -t "$outname" -Ssource="$filename"
```
the processor starts to process normally with tile counter starting from "Tile 1 of 16". However, after tile 16 of 16 the counter overflows and increases up to tile 60. The last lines in printout are

```
* -_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
*
* Tile 60 of 16
*
*** computeTileStack ***
TOA radiances
Lambdas
Solar fluxes
Flags
Ozone
Input assembly finished
libPath ANN: /home/mambauser/.snap/auxdata/fubcsiro
libPath eVT: /home/mambauser/.snap/auxdata/fubcsiro
Calling ANN using:    FUB_CSIRO
Calling eVT using:    eVT_FUB_CSIRO
Calling eVTTS using:  eVTTS_FUB_CSIRO
Calling sig using:    fun
- - - - - - nreVTin  =  10901, nreVTout  =   3703
echeck()  1 checkresin  ---   30446 (CT) 1103752 (OK)  106510 (VT)
echeck()  1 checkresout ---   14189 (CT) 1184556 (OK)   41963 (VT)
- - - - - - nreVTin  =  10901, nreVTout  =   3705
echeck()  2 checkresin  ---   30446 (CT) 1103752 (OK)  106510 (VT)
echeck()  2 checkresout ---    2712 (CT) 1196033 (OK)   41963 (VT)
- - - - - - nreVTin  =  10901, nreVTout  =   3704
echeck()  3 checkresin  ---   30446 (CT) 1103752 (OK)  106510 (VT)
echeck()  3 checkresout ---   26962 (CT) 1171783 (OK)   41963 (VT)
- - - - - - nreVTin  =  10902, nreVTout  =  10906
echeck()  4 checkresin  ---   26983 (CT) 1106147 (OK)  107578 (VT)
echeck()  4 checkresout ---  240597 (CT)  911457 (OK)   88654 (VT)
* -_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
```

The same issue happens if I do a dummy subset first. Then the tile counter increases until "Tile 602 of 154".

**Comment by SchroederT** [comment]
The underlying tile counter overflow issue is not caused by the plugin but by SNAP itself that provides 3 different processing pathways and that are implemented differently in the software. (1) standard GUI processing, (2) GPT processing using an XML input configuration file and (3) GPT single operator processing.

**(1) Standard GUI processing:**
Solved for plugin version 1.0.0.0.5.4 in combination with SNAP version 9 and latest updates applied only if an additional optimization of the System Performance is applied. To apply the optimization select 'Tools>Options>Performance' from the GUI menu and under 'System' use 'Compute' to calculate the parameters automatically. Press 'Apply' to save them. Under the processing section (same tab) the optimum tile size should be 512.

**(2) GPT processing using an XML input file:**
Solved for plugin version 1.0.0.0.5.4 in combination with SNAP version 9 and latest updates. No optimization of the System Performance is required.

**(3) GPT single operator processing:**
The issue still persists and requires further changes to be implemented by the SNAP development team. See also:
https://senbox.atlassian.net/browse/SNAP-1542
